<a href="https://colab.research.google.com/github/mokhivibes/ml_course_hometasks/blob/main/3_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Vazifa 1 — Array yaratish
'''np.zeros, np.ones, np.arange ishlatib quyidagilarni yarating:
5 ta noldan iborat array
3×3 birlardan iborat array
2 dan 20 gacha toq sonlar (qadam 2)
Har birining shape va dtype ni chiqaring.'''

import numpy as np

array = np.zeros(5)
print(array)
print(array.shape)
print(type(array))

array2 = np.ones((3, 3))
print(array2)
print(array2.shape)
print(type(array2))

toq_sonlar = np.arange(3, 20, 2)
print(toq_sonlar)
print(toq_sonlar.shape)
print(type(toq_sonlar))

[0. 0. 0. 0. 0.]
(5,)
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
<class 'numpy.ndarray'>
[ 3  5  7  9 11 13 15 17 19]
(9,)
<class 'numpy.ndarray'>

In [ ]:
#Vazifa 2 — Array xususiyatlari
'''Quyidagi arrayni yarating:
arr = np.array([[4, 7, 2], [1, 9, 5], [8, 3, 6]])
shape, ndim, size, dtype ni chiqaring.
Natijalarni o'zingiz tushuntiring — har biri nima degani?'''

arr = np.array([[4, 7, 2],
                [1, 9, 5],
                [8, 3, 6]])
print("Shape:" , arr.shape, ", Number of dimension:", arr.ndim, ", Size:", arr.size, ", Type:", arr.dtype)

Shape: (3, 3) , Number of dimension: 2 , Size: 9 , Type: int64

In [ ]:
#Vazifa 3 — Indexing va Slicing
'''Yuqoridagi arr dan:
Birinchi qatorni oling
Ikkinchi ustunni oling
9 elementini indeks bilan oling
Yuqori o'ng 2×2 qismni oling'''

arr = np.array([[4, 7, 2],
                [1, 9, 5],
                [8, 3, 6]])
qator1 = arr[0]
print(qator1)

ustun2 = arr[0:3, 1]
print(ustun2)

element9 = arr[1, 1]
print(element9)

qism2x2 = arr[0:2, 1:3]
print(qism2x2)

[4 7 2]
[7 9 3]
9
[[7 2]
 [9 5]]

In [ ]:
#Vazifa 4 — Random
'''np.random.seed(42) ishlatib:
1 dan 100 gacha 10 ta tasodifiy butun son yarating
0 dan 1 gacha 3×3 float array yarating
Har ikkalasining mean va max ini chiqaring.'''

np.random.seed(42)
arr = np.random.randint(1, 100, 10)
print(arr)
print("Mean:", arr.mean(), "Max:", arr.max())

arr2 = np.random.rand(3, 3)
print(arr2)
print("Mean:",arr2.mean(), "Max:", arr2.max())

[52 93 15 72 61 21 83 87 75 75]
Mean: 63.4 Max: 93
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Mean: 0.5084299233679132 Max: 0.9699098521619943

In [ ]:
#Vazifa 5 — 3D array
'''np.ones ishlatib 2×3×4 o'lchamli array yarating.
ndim, shape, size ni chiqaring va nima ekanligini tushuntiring
Birinchi 'qatlamdan' birinchi qatorni oling'''

array = np.ones((2,3,4))
print(array)
print(array.ndim, array.shape, array.size)
print(array[0, 0])

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4) 24
[1. 1. 1. 1.]

In [ ]:
#Uyga vazifa:
'''1-vazifa:
NumPy: 20 ta sondan massiv yarating va statistikani hisoblang'''

array = np.random.randint(0, 21, 20)
print(array)
mean = array.mean()
maxi = array.max()
mini = array.min()
summ = array.sum()
shape = array.shape
size = array.size
standard = array.std()
print(mean)
print(maxi)
print(mini)
print(summ)
print(shape)
print(size)
print(standard)

[ 2 16  4 16 16 16  1  1  4  0  0 18  1 20 11  5  3 10 16  5]
8.25
20
0
165
(20,)
20
6.934515123640585

In [ ]:
# 2-vazifa: Pandas

'''o'zingiz haqingizda DataFrame yarating (kamida 5 ustun)'''

import pandas as pd
my_info = {"Ism": ["Moxichexra"],
            "Familiya": ["Usmonova"],
            "Yosh": [22],
            "Til":["O'zbek"],
            "Kurs": [3]}
table_info = pd.DataFrame(my_info)
print(table_info)

          Ism  Familiya  Yosh     Til  Kurs
0  Moxichexra  Usmonova    22  O'zbek     3

In [ ]:
#3-vazifa
'''CSV faylni o'qing va describe() natijasini tahlil qiling'''

data = pd.read_csv("/content/talabalar - talabalar.csv.csv")
print(data.describe())

             yosh        baho        kurs
count  100.000000  100.000000  100.000000
mean    22.600000   77.080000    2.420000
std      2.651472   13.786745    1.147505
min     18.000000   55.000000    1.000000
25%     20.750000   65.000000    1.000000
50%     23.000000   77.500000    2.000000
75%     25.000000   89.500000    3.250000
max     26.000000  100.000000    4.000000

In [ ]:
#4-vazifa
'''groupby() bilan bitta savol toping va javobini yozing'''
mean_ball = data.groupby("yosh")['baho'].mean()
print(mean_ball)

yosh
18    81.222222
19    75.000000
20    85.900000
21    72.357143
22    77.571429
23    73.916667
24    82.000000
25    73.416667
26    76.200000
Name: baho, dtype: float64

In [ ]:
#5-vazifa:
'''Kaggle bilan tanishib chiqing va dataset yuklab darsda o'rgangan
bilimlaringizni qo'llang'''

!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.3)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (2.0.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.4.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle->opendatasets) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle->opendatasets) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (4.15.0)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [ ]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/aliyasaly1231/parental-genetics-and-child-trait-prediction-dataset/data")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: mokhivibes
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/aliyasaly1231/parental-genetics-and-child-trait-prediction-dataset
Downloading parental-genetics-and-child-trait-prediction-dataset.zip to ./parental-genetics-and-child-trait-prediction-dataset

100%|██████████| 145k/145k [00:00<00:00, 25.6MB/s]

In [ ]:
import pandas as pd
df = pd.read_csv("/content/parental-genetics-and-child-trait-prediction-dataset/parental_genetics_child_traits.csv")
df.head(21)
df.describe()

,Father_Age,Mother_Age,Father_Height_cm,Mother_Height_cm,Predicted_Child_Height_cm
count,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000
mean,37.650286,34.035857,173.970257,161.084257,167.595814
std,10.323333,9.447972,6.922160,5.971471,8.816473
min,20.000000,18.000000,155.000000,145.000000,140.600000
25%,29.000000,26.000000,169.200000,157.000000,161.100000
50%,38.000000,34.000000,174.000000,161.100000,167.700000
75%,47.000000,42.000000,178.700000,165.200000,174.200000
max,55.000000,50.000000,197.900000,185.000000,198.500000

In [ ]:
print(f"Shape of data: >>>>>{df.shape}\n")
print(f"First 20 people's data: >>>>>{df.tail(20)}\n")
print(f"Types of data: >>>>>{df.dtypes}\n")
print(f"Size of data: >>>>>{df.size}\n")
moderates = df["Predicted_Health_Risk"] == "Moderate"
df_clean = df.dropna()
moderates = df_clean[df_clean["Predicted_Health_Risk"] == "Moderate"]

print(f"Only the data of people who have moderate predicted health risk: >>>>>{moderates}")
df.groupby("Family_ID")["Father_Age"].max()

Shape of data: >>>>>(7000, 18)

First 20 people's data: >>>>>     Family_ID  Father_Age  Mother_Age  Father_Height_cm  Mother_Height_cm  \
6980  FAM06981          45          43             168.7             159.9
6981  FAM06982          53          25             181.6             156.8
6982  FAM06983          26          39             170.4             161.8
6983  FAM06984          47          42             175.0             155.7
6984  FAM06985          47          29             180.4             153.9
6985  FAM06986          33          26             167.2             157.7
6986  FAM06987          23          27             166.4             150.7
6987  FAM06988          37          27             191.6             168.2
6988  FAM06989          44          26             168.0             164.1
6989  FAM06990          26          43             185.3             155.8
6990  FAM06991          47          44             173.6             157.9
6991  FAM06992          24          48             171.0             165.6
6992  FAM06993          22          36             171.7             168.6
6993  FAM06994          50          23             173.6             161.6
6994  FAM06995          39          32             183.4             159.5
6995  FAM06996          38          46             179.3             151.2
6996  FAM06997          30          22             172.5             159.1
6997  FAM06998          22          31             160.9             154.2
6998  FAM06999          42          19             174.1             154.0
6999  FAM07000          26          40             174.9             168.4

     Father_Blood_Group Mother_Blood_Group Father_Eye_Color Mother_Eye_Color  \
6980                 O+                 B-            Green            Brown
6981                 B+                 A-            Hazel            Hazel
6982                AB-                 B+            Hazel             Gray
6983                 B+                 A+             Blue            Green
6984                 O+                 A+            Green            Brown
6985                 B+                 O+            Brown             Blue
6986                 A+                 A+            Brown            Green
6987                 A+                AB+            Brown            Brown
6988                 O+                AB+             Gray            Brown
6989                 B-                 O-             Blue            Hazel
6990                 A+                AB+            Brown            Hazel
6991                 O+                 A+            Green            Brown
6992                 A+                 B-             Blue            Brown
6993                 B-                 B+            Brown             Gray
6994                 O-                 O+            Hazel            Brown
6995                 A+                AB+            Green            Green
6996                 A+                 B+            Green            Brown
6997                 B+                 B-            Brown            Hazel
6998                 B-                 B+            Brown             Blue
6999                 A+                 B+            Green            Brown

     Father_Hair_Color Mother_Hair_Color Father_Skin_Tone Mother_Skin_Tone  \
6980             Black             Black            Olive           Medium
6981             Brown             Black            Light            Olive
6982            Blonde             Brown            Light            Olive
6983             Brown             Brown            Light            Light
6984            Blonde             Brown             Fair             Fair
6985             Black             Black             Fair            Light
6986             Brown             Brown           Medium           Medium
6987             Brown             Black            Olive            Olive
6988             Black            Blonde           Medium           Medium
6989             Brown             Brown            Olive           Medium
6990            Blonde             Brown           Medium           Medium
6991             Brown             Black             Fair            Light
6992             Black             Brown           Medium           Medium
6993             Brown            Blonde            Olive            Olive
6994             Brown             Black             Fair             Fair
6995             Black             Brown           Medium           Medium
6996             Black             Brown            Light             Dark
6997             Black             Brown             Dark             Dark
6998            Blonde             Black            Light             Dark
6999             Brown             Black            Olive            Light

     Family_Disease_History Child_Gender  Predicted_Child_Height_cm  \
6980                    NaN       Female                      159.3
6981               Multiple         Male                      173.4
6982               Multiple       Female                      165.4
6983           Hypertension       Female                      161.0
6984               Diabetes         Male                      171.6
6985               Diabetes         Male                      167.1
6986                    NaN         Male                      162.4
6987               Diabetes         Male                      186.2
6988               Diabetes       Female                      163.0
6989               Multiple         Male                      183.3
6990               Diabetes       Female                      161.6
6991          Heart Disease       Female                      159.6
6992          Heart Disease       Female                      159.0
6993               Multiple       Female                      162.5
6994                    NaN         Male                      187.6
6995                    NaN       Female                      155.5
6996           Hypertension         Male                      166.7
6997               Diabetes       Female                      153.6
6998           Hypertension         Male                      167.8
6999           Hypertension         Male                      177.0

     Predicted_Child_Blood_Group Predicted_Health_Risk
6980                          B+              Moderate
6981                         AB+                  High
6982                         AB-              Moderate
6983                         AB-                  High
6984                          A+                  High
6985                          B+                   Low
6986                          A-                   Low
6987                         AB-              Moderate
6988                          B+              Moderate
6989                          B-                  High
6990                          A+                  High
6991                          A+              Moderate
6992                         AB+                  High
6993                          B+                  High
6994                          O+              Moderate
6995                         AB+              Moderate
6996                         AB+              Moderate
6997                          B+              Moderate
6998                          B-              Moderate
6999                         AB+              Moderate

Types of data: >>>>>Family_ID                       object
Father_Age                       int64
Mother_Age                       int64
Father_Height_cm               float64
Mother_Height_cm               float64
Father_Blood_Group              object
Mother_Blood_Group              object
Father_Eye_Color                object
Mother_Eye_Color                object
Father_Hair_Color               object
Mother_Hair_Color               object
Father_Skin_Tone                object
Mother_Skin_Tone                object
Family_Disease_History          object
Child_Gender                    object
Predicted_Child_Height_cm      float64
Predicted_Child_Blood_Group     object
Predicted_Health_Risk           object
dtype: object

Size of data: >>>>>126000

Only the data of people who have moderate predicted health risk: >>>>>     Family_ID  Father_Age  Mother_Age  Father_Height_cm  Mother_Height_cm  \
1     FAM00002          34          24             185.5             152.2
3     FAM00004          40          26             161.0             157.8
4     FAM00005          38          35             175.7             160.7
7     FAM00008          30          42             174.7             149.6
10    FAM00011          43          33             169.7             161.5
...        ...         ...         ...               ...               ...
6991  FAM06992          24          48             171.0             165.6
6996  FAM06997          30          22             172.5             159.1
6997  FAM06998          22          31             160.9             154.2
6998  FAM06999          42          19             174.1             154.0
6999  FAM07000          26          40             174.9             168.4

     Father_Blood_Group Mother_Blood_Group Father_Eye_Color Mother_Eye_Color  \
1                    A+                 A+            Brown             Blue
3                    O+                AB-            Brown            Brown
4                    A-                 O+            Hazel            Brown
7                    O-                 O+            Green            Brown
10                   O+                 B+            Brown             Blue
...                 ...                ...              ...              ...
6991                 O+                 A+            Green            Brown
6996                 A+                 B+            Green            Brown
6997                 B+                 B-            Brown            Hazel
6998                 B-                 B+            Brown             Blue
6999                 A+                 B+            Green            Brown

     Father_Hair_Color Mother_Hair_Color Father_Skin_Tone Mother_Skin_Tone  \
1                Black             Brown            Olive           Medium
3                Black             Black             Dark             Dark
4                Brown             Black           Medium             Fair
7               Blonde             Black            Light            Light
10               Brown            Blonde             Fair             Fair
...                ...               ...              ...              ...
6991             Brown             Black             Fair            Light
6996             Black             Brown            Light             Dark
6997             Black             Brown             Dark             Dark
6998            Blonde             Black            Light             Dark
6999             Brown             Black            Olive            Light

     Family_Disease_History Child_Gender  Predicted_Child_Height_cm  \
1              Hypertension       Female                      164.0
3                  Diabetes         Male                      161.7
4                    Asthma         Male                      171.7
7                    Asthma       Female                      155.5
10                   Asthma         Male                      168.4
...                     ...          ...                        ...
6991          Heart Disease       Female                      159.6
6996           Hypertension         Male                      166.7
6997               Diabetes       Female                      153.6
6998           Hypertension         Male                      167.8
6999           Hypertension         Male                      177.0

     Predicted_Child_Blood_Group Predicted_Health_Risk
1                             A+              Moderate
3                             A-              Moderate
4                             A+              Moderate
7                             O+              Moderate
10                            B+              Moderate
...                          ...                   ...
6991                          A+              Moderate
6996                         AB+              Moderate
6997                          B+              Moderate
6998                          B-              Moderate
6999                         AB+              Moderate

[2541 rows x 18 columns]

Family_ID
FAM00001    48
FAM00002    34
FAM00003    27
FAM00004    40
FAM00005    38
            ..
FAM06996    38
FAM06997    30
FAM06998    22
FAM06999    42
FAM07000    26
Name: Father_Age, Length: 7000, dtype: int64